# Generated by Django 4.2.30 on 2026-06-19 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('recording', models.FileField(upload_to='recordings/', verbose_name='Bản ghi giọng bé')),
                ('asr_text', models.CharField(blank=True, max_length=255, verbose_name='Máy nghe được')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Điểm khớp (0–100)')),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Số sao (0–3)')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.childprofile', verbose_name='Bé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='catalog.word', verbose_name='Từ')),
            ],
            options={
                'verbose_name': 'Lần luyện phát âm',
                'verbose_name_plural': 'Lần luyện phát âm',
                'ordering': ['-created_at'],
            },
        ),
    ]
