# Generated by Django 4.2.30 on 2026-06-19 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name_en', models.CharField(max_length=100, verbose_name='Tên (tiếng Anh)')),
                ('name_vi', models.CharField(max_length=100, verbose_name='Tên (tiếng Việt)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Định danh')),
                ('icon', models.CharField(blank=True, default='📚', max_length=50, verbose_name='Biểu tượng')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('active', models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], default='Y', max_length=1, verbose_name='Đang dùng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Chủ đề',
                'verbose_name_plural': 'Chủ đề',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('text_en', models.CharField(max_length=100, verbose_name='Từ (tiếng Anh)')),
                ('text_vi', models.CharField(max_length=150, verbose_name='Nghĩa (tiếng Việt)')),
                ('phonetic', models.CharField(blank=True, max_length=150, verbose_name='Phiên âm (IPA)')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Hình minh hoạ')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Độ khó')),
                ('active', models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], default='Y', max_length=1, verbose_name='Đang dùng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='catalog.topic', verbose_name='Chủ đề')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Từ vựng',
                'verbose_name_plural': 'Từ vựng',
                'ordering': ['topic', 'text_en'],
            },
        ),
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('source', models.CharField(choices=[('tts', 'Máy đọc (TTS)'), ('recorded', 'Thu sẵn')], default='tts', max_length=10, verbose_name='Nguồn')),
                ('voice', models.CharField(blank=True, max_length=50, verbose_name='Giọng')),
                ('file', models.FileField(upload_to='audio/', verbose_name='Tệp âm thanh')),
                ('is_default', models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], default='N', max_length=1, verbose_name='Mặc định')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='catalog.word', verbose_name='Từ vựng')),
            ],
            options={
                'verbose_name': 'Audio phát âm',
                'verbose_name_plural': 'Audio phát âm',
                'ordering': ['word', '-is_default'],
            },
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('topic', 'text_en'), name='uniq_word_per_topic'),
        ),
    ]
