# Generated by Django 4.2.30 on 2026-07-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon_image',
            field=models.ImageField(blank=True, upload_to='images/topic/', verbose_name='Ảnh chủ đề'),
        ),
        migrations.AddField(
            model_name='topic',
            name='icon_static',
            field=models.CharField(blank=True, help_text='Đường dẫn trong static, vd icons/topic/animals.svg', max_length=120, verbose_name='SVG tĩnh'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.CharField(blank=True, default='📚', max_length=50, verbose_name='Biểu tượng (emoji)'),
        ),
    ]
