# Generated by Django 4.2.30 on 2026-06-19 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.SlugField(unique=True, verbose_name='Mã game')),
                ('name_vi', models.CharField(max_length=100, verbose_name='Tên game')),
                ('icon', models.CharField(blank=True, default='🎮', max_length=50, verbose_name='Biểu tượng')),
                ('module', models.CharField(max_length=50, verbose_name='Module xử lý')),
                ('min_words', models.PositiveSmallIntegerField(default=4, verbose_name='Số từ tối thiểu')),
                ('needs_image', models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], default='N', max_length=1, verbose_name='Cần hình')),
                ('needs_asr', models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], default='N', max_length=1, verbose_name='Cần chấm giọng')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('active', models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], default='Y', max_length=1, verbose_name='Đang dùng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Loại game',
                'verbose_name_plural': 'Loại game',
                'ordering': ['order', 'name_vi'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('stars', models.PositiveSmallIntegerField(default=0, verbose_name='Số sao (0–3)')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Điểm (số câu đúng)')),
                ('total', models.PositiveSmallIntegerField(default=0, verbose_name='Tổng số câu')),
                ('duration_sec', models.PositiveIntegerField(default=0, verbose_name='Thời lượng (giây)')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to='accounts.childprofile', verbose_name='Bé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='games.gametype', verbose_name='Loại game')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results', to='catalog.topic', verbose_name='Chủ đề')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Kết quả chơi',
                'verbose_name_plural': 'Kết quả chơi',
                'ordering': ['-created_at'],
            },
        ),
    ]
