# Generated by Django 4.2.30 on 2026-07-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_seed_recognition_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametype',
            name='hint_vi',
            field=models.CharField(blank=True, max_length=150, verbose_name='Câu hướng dẫn'),
        ),
    ]
