# Generated by Django 4.2.30 on 2026-07-03 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_managepasscode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.SlugField(unique=True, verbose_name='Mã huy hiệu')),
                ('name_vi', models.CharField(max_length=100, verbose_name='Tên huy hiệu')),
                ('icon', models.CharField(blank=True, default='🏅', max_length=50, verbose_name='Biểu tượng')),
                ('desc_vi', models.CharField(blank=True, max_length=150, verbose_name='Lời khen')),
                ('kind', models.CharField(choices=[('STARS', 'Tổng số sao'), ('GAMES', 'Số lượt chơi'), ('WORDS', 'Số từ đã luyện'), ('STREAK', 'Chuỗi ngày học')], max_length=10, verbose_name='Loại điều kiện')),
                ('threshold', models.PositiveIntegerField(default=1, verbose_name='Ngưỡng đạt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('active', models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], default='Y', max_length=1, verbose_name='Đang dùng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Huy hiệu',
                'verbose_name_plural': 'Huy hiệu',
                'ordering': ['order', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='ChildBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded', to='progress.badge', verbose_name='Huy hiệu')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.childprofile', verbose_name='Bé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Huy hiệu của bé',
                'verbose_name_plural': 'Huy hiệu của bé',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='childbadge',
            constraint=models.UniqueConstraint(fields=('child', 'badge'), name='uniq_child_badge'),
        ),
    ]
