# Generated by Django 4.2.30 on 2026-07-10 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0002_seed_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon_image',
            field=models.ImageField(blank=True, upload_to='images/badge/', verbose_name='Ảnh huy hiệu'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, default='🏅', max_length=50, verbose_name='Biểu tượng (emoji)'),
        ),
        migrations.CreateModel(
            name='PetStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('threshold', models.PositiveIntegerField(unique=True, verbose_name='Ngưỡng sao')),
                ('name_vi', models.CharField(max_length=100, verbose_name='Tên mốc')),
                ('emoji', models.CharField(blank=True, default='🌱', max_length=20, verbose_name='Emoji')),
                ('image', models.ImageField(blank=True, upload_to='images/pet/', verbose_name='Ảnh linh vật')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('active', models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], default='Y', max_length=1, verbose_name='Đang dùng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Linh vật (mốc lớn dần)',
                'verbose_name_plural': 'Linh vật (mốc lớn dần)',
                'ordering': ['threshold'],
            },
        ),
    ]
