# Generated by Django 4.2.30 on 2026-07-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_seed_pet_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon_static',
            field=models.CharField(blank=True, help_text='Đường dẫn trong static, vd icons/badge/stars-10.svg', max_length=120, verbose_name='SVG tĩnh'),
        ),
        migrations.AddField(
            model_name='petstage',
            name='icon_static',
            field=models.CharField(blank=True, help_text='Đường dẫn trong static, vd icons/pet/tree.svg', max_length=120, verbose_name='SVG tĩnh'),
        ),
    ]
