# Generated by Django 5.2.16 on 2026-07-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_seed_badges_higher'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstage',
            name='description',
            field=models.CharField(blank=True, help_text='Ví dụ: "Khởi đầu hành trình", "Tự tin giao tiếp"...', max_length=200, verbose_name='Câu mô tả'),
        ),
        migrations.AddField(
            model_name='petstage',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Số thứ tự cấp (1, 2, 3...)', verbose_name='Cấp độ'),
        ),
    ]
