# Generated by Django 4.2.30 on 2026-06-19 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=50, verbose_name='Tên bé')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Năm sinh')),
                ('avatar', models.CharField(blank=True, default='🐥', max_length=50, verbose_name='Avatar')),
                ('active', models.CharField(choices=[('Y', 'Có'), ('N', 'Không')], default='Y', max_length=1, verbose_name='Đang dùng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Phụ huynh')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Hồ sơ bé',
                'verbose_name_plural': 'Hồ sơ bé',
                'ordering': ['name'],
            },
        ),
    ]
